ibm.mq.additional-properties.WMQ_SHARE_CONV_ALLOWED=0
ibm.mq.application-name=kcg_frw
ibm.mq.channel=DEV.APP.SVRCONN
ibm.mq.conn-name=43.200.241.167(1414)
ibm.mq.queue-manager=QM1
ibm.mq.user=app
ibm.mq.password=passw0rd
logging.level.root=info
logging.level.com.jpmc.kcg=debug
logging.logback.rollingpolicy.max-file-size=10GB
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t][%X{X-GUID}]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
logging.pattern.file=%d{HH:mm:ss.SSS} %5p [%15.15t][%X{X-GUID}] %-40.40logger{39} : %m%n%wEx
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health
management.health.db.enabled=true
management.health.defaults.enabled=false
mybatis.configuration.cache-enabled=false
mybatis.configuration.default-statement-timeout=10
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.configuration.map-underscore-to-camel-case=true
server.shutdown=graceful
spring.application.name=kcg_frw
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@43.200.241.167/ORCLPDB1
spring.datasource.username=CPG
spring.datasource.password=CPG
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.jackson.deserialization.use-big-decimal-for-floats=true
spring.jackson.serialization.indent-output=false
spring.jackson.write.write-bigdecimal-as-plain=true
spring.jms.cache.session-cache-size=100
spring.jms.listener.session.transacted=true
spring.jms.template.receive-timeout=10s
spring.jms.template.session.transacted=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bwgtest01
spring.mail.password=zrlparovqhndbybj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.quartz.auto-startup=false
spring.quartz.job-store-type=jdbc
spring.quartz.overwrite-existing-jobs=true
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.scheduler.instanceId=kcg_frw.${system.instn-id:00}
spring.quartz.properties.org.quartz.threadPool.threadCount=1
spring.quartz.wait-for-jobs-to-complete-on-shutdown=true
################################################################################
################################################################################
################################################################################
system.cyber-ark=false
system.env-cd=production
system.cqe.ent.con=4
system.cqe.ent.rcv=TSSIAKCG.CQE.RCV
system.cqe.ent.snd=TSSIAKCG.CQE.SND
system.cqe.ift.con=4
system.cqe.ift.rcv=TSSIAKCG.CQE.IFT.RCV
system.cqe.ift.snd=TSSIAKCG.CQE.IFT.SND
system.cqe.rpr.con=4
system.cqe.rpr.rcv=TSSIAKCG.CQE.RPR.RCV
system.cqe.rpr.snd=TSSIAKCG.CQE.RPR.SND
system.gch.hof.con=4
system.gch.hof.rcv=TSSIAKCG.GCH.RCV
system.gch.hof.snd=TSSIAKCG.GCH.SND
system.kcg.ars.cmn=TSSIAKCG.KCG.ARS.CMN
system.kcg.ars.con=4
system.kcg.ati.cmn=TSSIAKCG.KCG.ATI.CMN
system.kcg.ati.con=4
system.kcg.cms.cmn=TSSIAKCG.KCG.CMS.CMN
system.kcg.cms.con=4
system.kcg.ent.cmn=TSSIAKCG.KCG.ENT.CMN
system.kcg.ent.con=4
system.kcg.gro.cmn=TSSIAKCG.KCG.GRO.CMN
system.kcg.gro.con=4
system.kcg.hof.cmn=TSSIAKCG.KCG.HOF.CMN
system.kcg.hof.con=4
system.kcg.ift.cmn=TSSIAKCG.KCG.IFT.CMN
system.kcg.ift.con=4
system.kcg.rpr.cmn=TSSIAKCG.KCG.RPR.CMN
system.kcg.rpr.con=4
system.kcg.bft.cmn=TSSIAKCG.KCG.BFT.CMN
system.kcg.bft.con=1
system.kcg.frw.cmn=TSSIAKCG.KCG.FRW.CMN
system.kcg.sim.cmn=TSSIAKCG.KCG.SIM.CMN
system.kcg.sim.con=4
system.kft.ars.con=4
system.kft.ars.rcv=TSSIAKCG.KFT.ARS.RCV
system.kft.ars.snd=TSSIAKCG.KFT.ARS.SND
system.kft.ati.con=4
system.kft.ati.rcv=TSSIAKCG.KFT.ATI.RCV
system.kft.ati.snd=TSSIAKCG.KFT.ATI.SND
system.kft.ent.con=4
system.kft.ent.rcv=TSSIAKCG.KFT.ENT.RCV
system.kft.ent.snd=TSSIAKCG.KFT.ENT.SND
system.kft.gro.con=4
system.kft.gro.rcv=TSSIAKCG.KFT.GRO.RCV
system.kft.gro.snd=TSSIAKCG.KFT.GRO.SND
system.kft.hof.con=4
system.kft.hof.rcv=TSSIAKCG.KFT.HOF.RCV
system.kft.hof.snd=TSSIAKCG.KFT.HOF.SND
system.kft.ift.con=4
system.kft.ift.rcv=TSSIAKCG.KFT.IFT.RCV
system.kft.ift.snd=TSSIAKCG.KFT.IFT.SND
system.kft.lcr.con=1
system.kft.lcr.rcv=TSSIAKCG.KFT.LCR.RCV
system.kft.lcr.snd=TSSIAKCG.KFT.LCR.SND
system.kft.rpr.con=4
system.kft.rpr.rcv=TSSIAKCG.KFT.RPR.RCV
system.kft.rpr.snd=TSSIAKCG.KFT.RPR.SND
system.kib.hof.con=4
system.kib.hof.rcv=TSSIAKCG.ITC.RCV
system.kib.hof.snd=TSSIAKCG.ITC.SND
system.lvb.ars.con=4
system.lvb.ars.rcv=TSSIAKCG.LVB.ARS.RCV
system.lvb.ars.snd=TSSIAKCG.LVB.ARS.SND
system.lvb.ati.con=4
system.lvb.ati.rcv=TSSIAKCG.LVB.ATI.RCV
system.lvb.ati.snd=TSSIAKCG.LVB.ATI.SND
system.lvb.cms.con=4
system.lvb.cms.rcv=TSSIAKCG.LVB.CMS.RCV
system.lvb.cms.snd=TSSIAKCG.LVB.CMS.SND
system.lvb.gro.con=4
system.lvb.gro.rcv=TSSIAKCG.LVB.GRO.RCV
system.lvb.gro.snd=TSSIAKCG.LVB.GRO.SND
system.lvb.hof.ack=TSSIAKCG.LVB.ACK.SND
system.lvb.hof.con=4
system.lvb.hof.rcv=TSSIAKCG.LVB.HOFI.RCV
system.lvb.hof.snd=TSSIAKCG.LVB.HOFI.SND
system.lvb.ift.con=4
system.lvb.ift.rcv=TSSIAKCG.LVB.IFT.RCV
system.lvb.ift.snd=TSSIAKCG.LVB.IFT.SND
system.lvb.rpr.con=4
system.lvb.rpr.rcv=TSSIAKCG.LVB.RPR.RCV
system.lvb.rpr.snd=TSSIAKCG.LVB.RPR.SND
system.mac.key1=1111122222
system.mac.key2=2222211111
system.ext.host=43.200.241.167
system.ext.port=6000
system.instn-id=01
system.psh-msg=true
system.sftp.back=/home/ec2-user/sftp/back
system.sftp.recv=/home/ec2-user/sftp/recv
system.sftp.send=/home/ec2-user/sftp/send
system.sftp.enote.back=/home/ec2-user/sftp/enote/back
system.sftp.enote.recv=/home/ec2-user/sftp/enote/recv
system.sftp.enote.send=/home/ec2-user/sftp/enote/send
system.shrd.back=/home/ec2-user/shrd/back
system.shrd.recv=/home/ec2-user/shrd/recv
system.shrd.send=/home/ec2-user/shrd/send
system.vault-key.test1=MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTE=
system.vault-key.test2=MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjI=
system.vo-test=false
